version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "hoangks5"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-on0fgoagdvpw"
s3_prefix = "hoangks5"
region = "ap-southeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
